codecov:
  require_ci_to_pass: yes

coverage:
  precision: 0      # number of decimals
  round: nearest    # how coverage is rounded
  range: "50...85"  # range of coverage colors

  status:
    project: no
    patch: no
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "test/*"
  - "test-dev/**/*"
