#ifndef INLINE4_TNPLUG_H
#define INLINE4_TNPLUG_H

/*
** This file was auto generated by idltool 51.6.
**
** It provides compatibility to OS3 style library
** calls by substituting functions.
**
** Do not edit manually.
*/ 

#ifndef EXEC_TYPES_H
#include <exec/types.h>
#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

/* Inline macros for Interface "main" */
#define AnnouncePlayer(version) ITNPlug->AnnouncePlayer(version) 
#define InitPlayer(playmode) ITNPlug->InitPlayer(playmode) 
#define OpenPlayer(openme, inTuneNet) ITNPlug->OpenPlayer(openme, inTuneNet) 
#define ClosePlayer(inTuneNet) ITNPlug->ClosePlayer(inTuneNet) 
#define DecodeFramePlayer(inTuneNet, outbuffer) ITNPlug->DecodeFramePlayer(inTuneNet, outbuffer) 
#define ExitPlayer(aplayer) ITNPlug->ExitPlayer(aplayer) 
#define TestPlayer(testme, testbuffer, totallength) ITNPlug->TestPlayer(testme, testbuffer, totalsize, testsize) 
#define SeekPlayer(inTuneNet, seconds) ITNPlug->SeekPlayer(inTuneNet, seconds) 
#define DoNotify(inTuneNet, item, value)
   
#endif /* INLINE4_TNPLUG_H */
