
TOPDIR	= ../..
OBJS	= ptpopen.o debug.o usleep.o
DFILES	= Makefile $(OBJS:.o=.c) unistd.h config.h \
	  in_xmp.dsp libxmp.dsp libxmp.dsw osdcomm.h xmp.dsp
DDIRS	= sys
CFILES	=
DCFILES	=

all:

include $(TOPDIR)/Makefile.rules

