
/* This file was generated by idltool 51.6. Do not edit */

#ifndef EXEC_TYPES_H
#include <exec/types.h>

#endif
#ifndef EXEC_EXEC_H
#include <exec/exec.h>
#endif
#ifndef EXEC_INTERFACES_H
#include <exec/interfaces.h>
#endif

#ifndef UTILITY_TAGITEM_H
#include <utility/tagitem.h>
#endif

extern ULONG                VARARGS68K _TNPlug_Obtain(struct TNPlugIFace *);
extern ULONG                VARARGS68K _TNPlug_Release(struct TNPlugIFace *);
extern struct audio_player * VARARGS68K _TNPlug_AnnouncePlayer(struct TNPlugIFace *, ULONG version);
extern BOOL                 VARARGS68K _TNPlug_InitPlayer(struct TNPlugIFace *, struct TuneNet * inTuneNet, ULONG playmode);
extern BOOL                 VARARGS68K _TNPlug_OpenPlayer(struct TNPlugIFace *, UBYTE * openme, struct TuneNet * inTuneNet);
extern VOID                 VARARGS68K _TNPlug_ClosePlayer(struct TNPlugIFace *, struct TuneNet * inTuneNet);
extern LONG                 VARARGS68K _TNPlug_DecodeFramePlayer(struct TNPlugIFace *, struct TuneNet * inTuneNet, WORD * outbuffer);
extern VOID                 VARARGS68K _TNPlug_ExitPlayer(struct TNPlugIFace *, struct audio_player * aplayer);
extern LONG                 VARARGS68K _TNPlug_TestPlayer(struct TNPlugIFace *, UBYTE * testme, UBYTE * testbuffer, ULONG totalsize, ULONG testsize);
extern LONG                 VARARGS68K _TNPlug_SeekPlayer(struct TNPlugIFace *, struct TuneNet * inTuneNet, ULONG seconds);
extern ULONG                VARARGS68K _TNPlug_DoNotify(struct TNPlugIFace *, struct TuneNet * inTuneNet, ULONG item, ULONG value);


STATIC CONST APTR main_vectors[] =
{
    (void *)_TNPlug_Obtain,
    (void *)_TNPlug_Release,
    (void *)NULL,
    (void *)NULL,
    (void *)_TNPlug_AnnouncePlayer,
    (void *)_TNPlug_InitPlayer,
    (void *)_TNPlug_OpenPlayer,
    (void *)_TNPlug_ClosePlayer,
    (void *)_TNPlug_DecodeFramePlayer,
    (void *)_TNPlug_ExitPlayer,
    (void *)_TNPlug_TestPlayer,
    (void *)_TNPlug_SeekPlayer,
    (void *)_TNPlug_DoNotify,
    (APTR)-1
};
