#!/bin/sh

#
# Run either xmp or xxmp with the command-line arguments
#

xmp_opts=""
if [ -f /etc/xmp-view.conf ]; then
	. /etc/xmp-view.conf
fi

if test "$DISPLAY" = ""; then
	xmp $xmp_opts $*
else
	xxmp $xmp_opts $*
fi

# End of file.
