/* Extended Module Player
 * Copyright (C) 1996-2011 Claudio Matsuoka and Hipolito Carraro Jr
 *
 * This file is part of the Extended Module Player and is distributed
 * under the terms of the GNU General Public License. See doc/COPYING
 * for more information.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "xmp.h"
#include "common.h"
#include "driver.h"
#include "synth.h"
#include "spectrum.h"
#include "ym2149.h"


static void synth_setpatch(int c, uint8 * data)
{
}

/*
 * Tone Generator Control
 * (Registers R0, R1, R2, R3, R4, R5)
 * 
 * The frequency of each square wave generated by the three Tone
 * Generators (one each for Channels A, B, and C) is obtained in the
 * PSG by first counting down the input clock by 16, then by further
 * counting down the result by the programmed 12-bit Tone Period
 * value. Each 12-bit value is obtained in the PSG by combining the
 * contents of the relative Coarse and Fine Tune registers, as illustrated
 * in the following:
 * 
 *    Coarse Tune Registers     Channel            Fine Tune Register
 *           R1                    A                      R0
 *           R3                    B                      R2
 *           R5                    C                      R4
 * 
 *    B7 B6 B5 B4 B3 B2 B1 B0                      B7 B6 B5 B4 B3 B2 B1 B0
 *    \_________/ |           \                   /                      /
 *        \/      |            \                 /                      /
 *     NOT USED   |             | ______________/                      /
 *               /              |/                              ______/
 *             TP11 TP10 TP9 TP8 TP7 TP6 TP5 TP4 TP3 TP2 TP1 TP0
 *                 12-bit Tone Period (TP) to Tone Generator
 */

static void synth_setnote(int c, int note, int bend)
{
}

/*
 * Amplitude Control
 * (Registers R8, R9, R10)
 * 
 * The amplitudes of the signals generated by each of the three D/A
 * Converters (one each for Channels A, B, and C) is determined by the
 * contents of the lower 5 bits (B4--B0) of registers R8, R9, and R10 as
 * illustrated in the following:
 * 
 *        Amplitude Control Register    Channel
 *                  R8                    A
 *                  R9                    B
 *                  R10                   C
 * 
 *                B7 B6 B5 B4 B3 B2 B1 B0
 *                \______/  | \________/
 *                   \/     |     \/
 *                NOT USED  |     L3 L2 L1 L0
 *                          |     4-bit "fixed" amplitude Level.
 *                          |
 *                          |
 *                    amplitude "Mode"
 * 
 */

static void synth_setvol(int c, int vol)
{
}

static int synth_init(int freq)
{
	YM_init();
	YM_sampling_rate(freq);

	return 0;
}

static int synth_reset()
{
	return YM_reset();
}

static int synth_deinit()
{
	synth_reset();

	return 0;
}

static void synth_mixer(int *tmp_bk, int count, int vl, int vr, int stereo)
{
	if (!tmp_bk)
		return;

	//YM3812UpdateOne(0, tmp_bk, count, vl, vr, stereo);
	
}


struct xmp_synth_info synth_spectrum = {
	synth_init,
	synth_deinit,
	synth_reset,
	synth_setpatch,
	synth_setnote,
	synth_setvol,
	synth_mixer
};

