import_extra_settings

cmake "${INPUTS_EXTRA_SETTINGS[@]}" \
  -B ${PATH_FIXER_CHECKOUT_PATH}/build \
  -DCMAKE_INSTALL_PREFIX=${PATH_FIXER_INSTALL_PATH} \
  -DCMAKE_BUILD_TYPE=${INPUTS_BUILD_TYPE} \
  ${CMAKE_OPTS} \
  -DBUILD_TESTS=ON
