/**
 * Chip Player JS - VGMusic Metadata Parsing Strategy
 *
 * Extracts rich metadata (Title, Game, Sequencer/Contributor, System, MD5)
 * from VGMusic.com `index.html` sidecar files generated by VGMusic.com Indexer.
 */

const fs = require('fs');
const path = require('path');
const { cleanString } = require('./metadata-utils');

// In-memory cache of parsed index.html data mapped by absolute file path
const dirCache = new Map();

/**
 * Decode basic HTML entities commonly found in VGMusic index.html files.
 */
function unescapeHtml(str) {
  if (!str) return '';
  return str
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#039;/g, "'")
    .replace(/&nbsp;/g, ' ')
    .replace(/&#(\d+);/g, (_, d) => String.fromCharCode(parseInt(d, 10)));
}

/**
 * Resolve the absolute path to a file or its directory.
 */
function resolveFullPath(relPath) {
  if (path.isAbsolute(relPath)) {
    return relPath;
  }

  const candidates = [
    path.resolve(relPath),
    path.resolve('./catalog', relPath),
    path.resolve(__dirname, '../catalog', relPath),
    path.resolve('/Users/montag/Music/Chip Archive', relPath),
  ];

  for (const cand of candidates) {
    if (fs.existsSync(cand)) {
      return cand;
    }
  }

  return path.resolve(relPath);
}

/**
 * Locate the sidecar (index.json or index.html) for a given MIDI relative or absolute path.
 * Checks:
 * 1. Same directory (standard flat VGMusic structure)
 * 2. Parent directory (when files are organized into game subfolders)
 */
function findSidecar(relPath) {
  const fullPath = resolveFullPath(relPath);
  const dir = path.dirname(fullPath);
  const candidates = [dir, path.dirname(dir)];

  for (const d of candidates) {
    const jsonPath = path.join(d, 'index.json');
    if (fs.existsSync(jsonPath)) {
      return { type: 'json', path: jsonPath };
    }
    const htmlPath = path.join(d, 'index.html');
    if (fs.existsSync(htmlPath)) {
      return { type: 'html', path: htmlPath };
    }
  }

  return null;
}

/**
 * Backward-compatible helper to locate index.html.
 */
function findIndexHtml(relPath) {
  const sidecar = findSidecar(relPath);
  if (sidecar && sidecar.type === 'html') return sidecar.path;
  const fullPath = resolveFullPath(relPath);
  const dir = path.dirname(fullPath);
  const candHtml1 = path.join(dir, 'index.html');
  if (fs.existsSync(candHtml1)) return candHtml1;
  const candHtml2 = path.join(path.dirname(dir), 'index.html');
  if (fs.existsSync(candHtml2)) return candHtml2;
  return null;
}

/**
 * Parses an index.json manifest into a structured lookup map.
 */
function parseIndexJson(jsonPath) {
  if (dirCache.has(jsonPath)) {
    return dirCache.get(jsonPath);
  }

  const fileMap = new Map();
  let systemName = null;

  try {
    const raw = fs.readFileSync(jsonPath, 'utf8');
    const data = JSON.parse(raw);
    systemName = data.system || null;

    if (data.files) {
      for (const [fn, meta] of Object.entries(data.files)) {
        fileMap.set(fn.toLowerCase(), {
          title: meta.title,
          game: meta.game,
          system: meta.system || systemName,
          contributor: meta.contributor || null,
          md5: meta.md5 || null,
        });
      }
    }
  } catch (err) {
    console.error(`[VGMusic] Failed to parse sidecar ${jsonPath}:`, err.message);
  }

  const result = { system: systemName, files: fileMap };
  dirCache.set(jsonPath, result);
  return result;
}

/**
 * Get sidecar data from either index.json or index.html.
 */
function getSidecarData(sidecar) {
  if (!sidecar) return { system: null, files: new Map() };
  if (sidecar.type === 'json') return parseIndexJson(sidecar.path);
  return parseIndexHtml(sidecar.path);
}

/**
 * Parses a VGMusic index.html file into a structured lookup map.
 * Results are cached in-memory for O(1) lookups per file.
 *
 * @param {string} htmlPath Absolute path to index.html
 * @returns {{ system: string|null, files: Map<string, object> }}
 */
function parseIndexHtml(htmlPath) {
  if (dirCache.has(htmlPath)) {
    return dirCache.get(htmlPath);
  }

  const fileMap = new Map();
  let systemName = null;

  try {
    const content = fs.readFileSync(htmlPath, 'utf8');

    // Extract System from <title>VGMusic.com - (.*) Music</title>
    const sysMatch = content.match(/<title>VGMusic\.com\s*-\s*([^<]+?)(?:\s*Music)?<\/title>/i);
    if (sysMatch) {
      systemName = cleanString(unescapeHtml(sysMatch[1].trim()));
    }

    let currentGame = null;
    const rowRegex = /<tr[^>]*>([\s\S]*?)(?:<\/tr>|(?=<tr)|$)/gi;
    let match;

    while ((match = rowRegex.exec(content)) !== null) {
      const row = match[1];

      // Check for Game Title Header:
      // <tr class="header"><td class="header" colspan="5"><a name="...">Game Title</a></td></tr>
      const headerMatch = row.match(/<td\s+class=["']?header["']?[^>]*>(?:<a[^>]*>)?([^<]+)/i);
      if (headerMatch) {
        const rawGame = cleanString(unescapeHtml(headerMatch[1].trim()));
        if (rawGame && rawGame !== '&nbsp;' && !rawGame.includes('SONG TITLE')) {
          currentGame = rawGame;
        }
        continue;
      }

      // Check for Song Row:
      // <td><a href="filename.mid">Song Title</a>
      const songMatch = row.match(/<td><a\s+href=(?:"([^"]+\.mid[i]?)"|'([^']+\.mid[i]?)'|([^\s>]+\.mid[i]?))[^>]*>([\s\S]*?)<\/a>/i);
      if (songMatch && currentGame) {
        let href = (songMatch[1] || songMatch[2] || songMatch[3]).trim();
        try {
          href = decodeURIComponent(href);
        } catch (e) {}

        const title = cleanString(unescapeHtml(songMatch[4].replace(/<[^>]+>/g, '').trim()));

        // In HTML 4.01 loose DTD, <td> cells often omit </td> closing tags.
        // Split by <td to cleanly extract all cell values.
        const cells = row
          .split(/<td[^>]*>/i)
          .slice(1)
          .map(c => cleanString(unescapeHtml(c.replace(/<[^>]+>/g, '').trim())));

        // cells[0] = Song Title
        // cells[1] = File Size (e.g. "1862 bytes")
        // cells[2] = Sequencer (e.g. "Stickmaster Felix")
        // cells[3] = Comments
        let contributor = null;
        if (cells.length >= 3 && cells[2] && cells[2] !== '&nbsp;') {
          contributor = cells[2];
        }

        // Extract MD5 hash from comments link:
        // <a href="../../../../file/568d7a8829b5e9e511ceec210626804c.html#disqus_thread">Comments</a>
        const md5Match = row.match(/\/file\/([a-f0-9]{32})\.html/i);
        const md5 = md5Match ? md5Match[1].toLowerCase() : null;

        const baseKey = path.basename(href).toLowerCase();
        fileMap.set(baseKey, {
          title,
          game: currentGame,
          system: systemName,
          contributor,
          md5,
        });
      }
    }
  } catch (err) {
    console.error(`[VGMusic] Failed to parse sidecar ${htmlPath}:`, err.message);
  }

  const result = { system: systemName, files: fileMap };
  dirCache.set(htmlPath, result);
  return result;
}

/**
 * Metadata strategy implementation for VGMusic files.
 *
 * @param {Buffer} buf Raw MIDI file buffer
 * @param {string|null} relPath Relative or absolute file path
 * @returns {object} Extracted metadata: { title, game, system, contributor, artist, md5 }
 */
function parseMidiVgmusic(buf, relPath) {
  if (!relPath) {
    return { title: null, game: null, system: null, contributor: null, artist: null, md5: null };
  }

  const fileName = path.basename(relPath);
  const baseKey = fileName.toLowerCase();
  const dirName = path.basename(path.dirname(relPath)).toLowerCase();
  const gameKey = `${dirName}/${baseKey}`;

  const sidecar = findSidecar(relPath);
  if (sidecar) {
    const { system, files } = getSidecarData(sidecar);
    const entry = files.get(gameKey) || files.get(baseKey);

    if (entry) {
      const rawSystem = entry.system || system;
      const cleanSystem = (rawSystem && !rawSystem.startsWith('-')) ? rawSystem : null;
      return {
        title: entry.title || path.basename(fileName, path.extname(fileName)),
        game: entry.game,
        system: cleanSystem,
        contributor: entry.contributor,
        artist: null, // VGMusic lists sequencers (contributor), not original composers
        md5: entry.md5 || null,
      };
    }
  }

  // Fallback if not indexed in sidecar
  return {
    title: path.basename(fileName, path.extname(fileName)),
    game: null,
    system: null,
    contributor: null,
    artist: null,
    md5: null,
  };
}

module.exports = {
  parseMidiVgmusic,
  parseIndexHtml,
  parseIndexJson,
  findSidecar,
  findIndexHtml,
  getSidecarData,
};
