all: midiplay

midiplay: adlmidiplay.o wave_writer.o
	g++ $^ -L../../bin -ladlmidi -lSDL2 -o ../../bin/adlmidiplay
	rm *.o

adlmidiplay.o: adlmidiplay.cpp
	g++ -c $^ -I.. -o adlmidiplay.o

wave_writer.o: wave_writer.c
	gcc -c $^ -I.. -o wave_writer.o

