export default [
  {
    title: 'Super Nintendo (SPC)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://66.90.93.122/soundfiles/nintendo-snes-spc/',
    files: [
      "donkey-kong-country/07%20Aquatic%20Ambiance.spc",
      "donkey-kong-country/10%20Mine%20Cart%20Madness.spc",
      "evo-search-for-eden/01%20The%20Origin%20of%20Gaia.spc",
    ]
  },
  {
    title: 'MIDI',
    url_prefix: 'songs/',
    files: [
      'all_night_long.mid',
      'christmas.mid',
      'KOOLTHIN.MID',
      'majicalljarr.mid',
      'neptune.mid',
      'rach3_1.mid',
      'rach3_2.mid',
      'rite-of-spring.mid',
      'STACCATO.MID',
      'Astro_Guy.mid',
      'DESCENT.MID',
      'GAME14.MID',
      'GAME18.MID',
      'GAME22.MID',
      'swanlake.mid',
      'syrinx.mid',
      'take5.mid',
    ],
  },
  {
    title: 'Local GME',
    url_prefix: 'songs/',
    files: [
      "04_realblue.nsf",
      "28_zjam300.nsf",
      "35_giantsteps.nsf",
      "Shovel_Knight_Music.nsf",
      "ThunderForce4.gym",
      'SFORCE2_003 - Town.gym',
      'SFORCE2_015 - Sad Theme 1.gym',
      'SFORCE2_027 - Goddess Mitula.gym',
      "wt-01.spc",
      "monx-AllYouGot.nsf",
      "monx-herveroy.nsf",
      "monx-HuGH2.nsf",
      "monx-OlympicHeroes.nsf",
      "monx-trash.nsf",
      'scriabin2.nsf',
    ],
  },
  {
    title: 'Local XMP',
    url_prefix: 'songs/',
    files: [
      "dd-smkr.xm",
      "tr3cheato.it",
      "ut-firebr.xm",
      "Death Rally/MENUTUNE.S3M",
      "Jazz Jackrabbit/Menu.s3m",
      "One Must Fall 2097/03-MENU.S3M",
      "Unreal Tournament/16 - Razorback (Unreal Mix) [Peter Hajba].it",
    ],
  },
  {
    title: 'Super Nintendo (RSN) (currently disabled)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://snesmusic.org/v2/download.php?spcNow=',
    files: [
      "smw&.rsn",
      "yc&.rsn",
      "yi&.rsn",
    ]
  },
  {
    title: 'http://rainwarrior.ca (Brad Smith)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://rainwarrior.ca/',
    files: [
      'music/moon8.nsfe',
      'projects/nes/2a03puritans.nsfe',
    ]
  },
  {
    title: 'Nintendo (NSF)',
    url_prefix: 'https://www.mattmontag.com/vgm/nsf/',
    files: [
      "8 Eyes.nsfe",
      "1943.nsfe",
      "A Boy and His Blob.nsfe",
      "Abadox.nsfe",
      "Action 52.nsfe",
      "Addams Family Pugsley's Scavenger Hunt.nsfe",
      "Adventure Island 2.nsfe",
      "Adventure Island.nsfe",
      "Adventures In The Magic Kingdom.nsfe",
      "Adventures of Bayou Billy.nsfe",
      "Adventures of Dino Riki.nsfe",
      "Adventures of Lolo 2.nsfe",
      "Adventures of Lolo 3.nsfe",
      "Adventures of Lolo.nsfe",
      "Ai Senshi Nicol.nsfe",
      "Air Fortress.nsfe",
      "Akumajou Densetsu.nsfe",
      "Aladdin (Unlicensed).nsfe",
      "Aladdin.nsfe",
      "Alien 3.nsfe",
      "Anticipation.nsfe",
      "Argos No Senshi.nsfe",
      "Arumana no Kiseki (FDS).nsfe",
      "Asterix.nsfe",
      "Astyanax.nsfe",
      "Bad Dudes.nsfe",
      "Bards Tale (Japan).nsfe",
      "Batman Return of the Joker.nsfe",
      "Batman Returns.nsfe",
      "Batman.nsfe",
      "Battletoads & Double Dragon.nsfe",
      "Battletoads.nsfe",
      "Beauty and the Beast.nsfe",
      "Big Nose the Caveman.nsfe",
      "Bionic Commando.nsfe",
      "Blades of Steel.nsfe",
      "Blaster Master.nsfe",
      "Booby Kids.nsfe",
      "Bram Stoker's Dracula.nsfe",
      "Bubble Bobble 2.nsfe",
      "Bubble Bobble.nsfe",
      "Bucky O' Hare.nsfe",
      "Burger Time.nsfe",
      "Caesars Palace.nsfe",
      "California Games.nsfe",
      "Captain America.nsfe",
      "Captain Skyhawk.nsfe",
      "Castlevania 2.nsfe",
      "Castlevania 3.nsfe",
      "Castlevania.nsfe",
      "Chip 'N Dale Rescue Rangers.nsfe",
      "Chip n' Dale Rescue Rangers 2.nsfe",
      "Choujin Sentai Jetman.nsfe",
      "Choujinrou Senki Warwolf.nsfe",
      "Clash at Demonhead.nsfe",
      "Cobra Triangle.nsfe",
      "Cocoron.nsfe",
      "Commando.nsfe",
      "Conquest of the Crystal Palace.nsfe",
      "Contra (Japan).nsfe",
      "Contra Force.nsfe",
      "Contra.nsfe",
      "Cowboy Kid.nsfe",
      "Crisis Force.nsfe",
      "Crystalis.nsfe",
      "Darkwing Duck.nsfe",
      "Deadly Towers.nsfe",
      "Deja Vu.nsfe",
      "Demon Sword.nsfe",
      "Doki Doki Panic.nsfe",
      "Donkey Kong Country 4.nsfe",
      "Donkey Kong FDS.nsfe",
      "Donkey Kong.nsfe",
      "Double Dragon 1.nsfe",
      "Double Dragon 2.nsfe",
      "Double Dragon 3.nsfe",
      "Dr. Mario.nsfe",
      "Dracula II (FDS).nsfe",
      "Dragon Fighter.nsfe",
      "Dragon Quest 4.nsfe",
      "Dragon Warrior 2.nsfe",
      "Dragon Warrior.nsfe",
      "Dragoon X Omega II (v1.26).nsfe",
      "Drop Zone.nsfe",
      "Duck Hunt (VS).nsfe",
      "Duck Hunt.nsfe",
      "Duck Tales Prototype.nsfe",
      "Duck Tales.nsfe",
      "DuckTales2.nsfe",
      "Erik The Viking.nsfe",
      "Esper Dream 2.nsfe",
      "Excitebike.nsfe",
      "Falsion.nsfe",
      "Famicom Grand Prix II - 3D Hot Rally.nsfe",
      "Fantasy Zone (Japan).nsfe",
      "Fantasy Zone.nsfe",
      "Faxanadu.nsfe",
      "Ferrari Grand Prix Challenge.nsfe",
      "Fester's Quest.nsfe",
      "Final Fantasy 1.nsfe",
      "Final Fantasy 2.nsfe",
      "Final Fantasy 3.nsfe",
      "Final Mission.nsfe",
      "Fire 'N Ice.nsfe",
      "Fire Emblem Gaiden.nsfe",
      "Fire Emblem.nsfe",
      "Flying Dragon.nsfe",
      "Flying DragonHiryuNoKen.nsfe",
      "Flying Warriors.nsfe",
      "Freedom Force.nsfe",
      "Friday the 13th.nsfe",
      "Fudou Myouou Den.nsfe",
      "Gargoyle's Quest 2.nsfe",
      "Getsufuu Maden.nsfe",
      "Ghostbusters 2.nsfe",
      "Ghosts 'n Goblins.nsfe",
      "Ghoul School.nsfe",
      "Gimmick!.nsfe",
      "Godzilla.nsfe",
      "Goonies II.nsfe",
      "Goonies.nsfe",
      "Gotcha! The Sport.nsfe",
      "Gradius II.nsfe",
      "Gradius.nsfe",
      "Gremlins 2.nsfe",
      "Guardian Legend.nsfe",
      "Guerilla War.nsfe",
      "Gun Nac.nsfe",
      "Hebereke.nsfe",
      "Hero Quest.nsfe",
      "Highway Star.nsfe",
      "Hydlide 3 - Yami Kara no Houmonsha.nsfe",
      "Ice Climbers.nsfe",
      "Immortal, The.nsfe",
      "Incredible Crash Test Dummies.nsfe",
      "Indiana Jones and the Last Crusade.nsfe",
      "Ironsword - Wizards & Warriors 2.nsfe",
      "Isolated Warrior.nsfe",
      "Jackal.nsfe",
      "James Bond Jr.nsfe",
      "Journey to Silius.nsfe",
      "Jungle Book, The.nsfe",
      "Jurassic Park.nsfe",
      "Karate Kid.nsfe",
      "Karnov.nsfe",
      "Kick Master.nsfe",
      "Kid Icarus.nsfe",
      "King Kong 2.nsfe",
      "Kirby's Adventure.nsfe",
      "Kiwi Kraze [New Zealand Story].nsfe",
      "Klax.nsfe",
      "Kouryuu Densetsu Villgust Gaiden.nsfe",
      "Krion Conquest, The.nsfe",
      "Kujaku Ou 2.nsfe",
      "Lagrange Point.nsfe",
      "Laser Invasion.nsfe",
      "Last Action Hero.nsfe",
      "Legacy of the Wizard.nsfe",
      "Legendary Wings.nsfe",
      "Lethal Weapon.nsfe",
      "Lifeforce.nsfe",
      "Link No Bouken.nsfe",
      "Little Nemo - The Dream Master.nsfe",
      "Little Samson.nsfe",
      "Low G Man.nsfe",
      "M.C. Kids.nsfe",
      "Madara.nsfe",
      "Magic Johnson's Fast Break.nsfe",
      "Maniac Mansion.nsfe",
      "Marble Madness.nsfe",
      "Mario Bros.nsfe",
      "Mario's Time Machine.nsfe",
      "Marvel's X-Men.nsfe",
      "Maze of Galious 2.nsfe",
      "Mega Man 1.nsfe",
      "Mega Man 2.nsfe",
      "Mega Man 3.nsfe",
      "Mega Man 4.nsfe",
      "Mega Man 5.nsfe",
      "Mega Man 6.nsfe",
      "Metal Gear.nsfe",
      "Metal Storm.nsfe",
      "Metroid FDS.nsfe",
      "Metroid.nsfe",
      "Mighty Final Fight.nsfe",
      "Mike Tyson's Punch Out!!.nsfe",
      "Milon's Secret Castle.nsfe",
      "Mission Impossible.nsfe",
      "Mitsume ga Tooru.nsfe",
      "Moai Kun.nsfe",
      "Monopoly.nsfe",
      "Monster in My Pocket.nsfe",
      "Monster Party.nsfe",
      "Moon Crystal.nsfe",
      "Mother.nsfe",
      "NARC.nsfe",
      "New Ghostbusters 2.nsfe",
      "Nightmare on Elm Street.nsfe",
      "Ninja Gaiden 1.nsfe",
      "Ninja Gaiden 2.nsfe",
      "Ninja Gaiden 3 - The Ancient Ship of Doom.nsfe",
      "Over Horizon.nsfe",
      "Overlord.nsfe",
      "Palamedes 2 - Star Twinkles.nsfe",
      "Panic Restaurant.nsfe",
      "Parodius Da!.nsfe",
      "Pescatore.nsfe",
      "Pictionary.nsfe",
      "Pin-Bot.nsfe",
      "Pinball Quest.nsfe",
      "Pipe Dream.nsfe",
      "Platoon.nsfe",
      "Popeye.nsfe",
      "POW.nsfe",
      "Power Blade II.nsfe",
      "Power Blade.nsfe",
      "Punch-Out (Arcade).nsfe",
      "Puss 'n Boots.nsfe",
      "Puyo Puyo.nsfe",
      "Qix.nsfe",
      "Rambo.nsfe",
      "RC Pro-Am.nsfe",
      "River City Ransom.nsfe",
      "Robin Hood - Prince of Thieves.nsfe",
      "Robocop 3.nsfe",
      "Robocop.nsfe",
      "RodLand.nsfe",
      "RollerBall.nsfe",
      "Rollergames.nsfe",
      "Rush 'n' Attack.nsfe",
      "Rygar.nsfe",
      "SCAT.nsfe",
      "Section Z.nsfe",
      "Sesame Street ABC - 123.nsfe",
      "Shadow of the Ninja.nsfe",
      "Shadowgate.nsfe",
      "Shatterhand JP [Tokkyuu Shirei - Solbrain].nsfe",
      "Shatterhand.nsfe",
      "Silver Surfer.nsfe",
      "Skate or Die 2.nsfe",
      "Skate or Die!.nsfe",
      "Ski or Die.nsfe",
      "Sky Shark.nsfe",
      "Smurfs, The.nsfe",
      "Snake Rattle 'n' Roll.nsfe",
      "Snakes Revenge.nsfe",
      "Snow Bros.nsfe",
      "Solstice.nsfe",
      "Startropics 2 - Zoda's Revenge.nsfe",
      "Startropics.nsfe",
      "Stinger.nsfe",
      "Street Fighter 2010 - Final Fight.nsfe",
      "Strider Hiryu.nsfe",
      "StriderHiryu.nsfe",
      "Super Contra.nsfe",
      "Super Dodge Ball.nsfe",
      "Super Donkey Kong (Pirate).nsfe",
      "Super Mario Bros 1.nsfe",
      "Super Mario Bros 2.nsfe",
      "Super Mario Bros 3.nsfe",
      "Super Mario Bros. 1 and 2.nsfe",
      "Super Spike V Ball.nsfe",
      "Super Spy Hunter.nsfe",
      "Sweet Home.nsfe",
      "Sword Master.nsfe",
      "Swords and Serpents.nsfe",
      "Taboo - The Sixth Sense.nsfe",
      "Tale Spin.nsfe",
      "Target Renegade.nsfe",
      "Tecmo World Wrestling.nsfe",
      "Teenage Mutant Ninja Turtles 2.nsfe",
      "Teenage Mutant Ninja Turtles III - The Manhattan Project.nsfe",
      "Teenage Mutant Ninja Turtles.nsfe",
      "Terminator 2.nsfe",
      "Tetris (Nintendo).nsfe",
      "Tetris (Tengen).nsfe",
      "The Little Mermaid.nsfe",
      "Time Diver Eon Man.nsfe",
      "Time Lord.nsfe",
      "Tiny Toon Adventures.nsfe",
      "Tom and Jerry.nsfe",
      "Tombs & Treasure.nsfe",
      "Top Gun - Dual Fighters.nsfe",
      "Total Recall.nsfe",
      "Toukon Club.nsfe",
      "Toxic Crusaders.nsfe",
      "Treasure Master.nsfe",
      "Trojan.nsfe",
      "Uninvited.nsfe",
      "Vs Excitebike.nsfe",
      "Wai Wai World 2.nsfe",
      "Wai Wai World.nsfe",
      "Wario's Woods.nsfe",
      "Werewolf - The Last Warrior.nsfe",
      "Wild Gunman.nsfe",
      "Willow.nsfe",
      "Wizards & Warriors 3.nsfe",
      "Wizards & Warriors.nsfe",
      "Wolverine.nsfe",
      "Wurm.nsfe",
      "WWF WrestleMania Challenge.nsfe",
      "WWF WrestleMania.nsfe",
      "Xexyz.nsfe",
      "Yoshi.nsfe",
      "Yoshi's Cookie.nsfe",
      "Ys - Ancient Ys Vanished Omen.nsfe",
      "Ys 2 - Ancient Ys Vanished - Final Chapter.nsfe",
      "Ys 3 - Wanderers from Ys (1991)(Falcom)(26 Tracks).nsfe",
      "Zelda II - The Adventure of Link.nsfe",
      "Zelda.nsfe",
      "Zen Intergalactic Ninja.nsfe",
      "Zombie Nation.nsfe"
    ]
  }
];
