export default [
  {
    title: 'Super Nintendo (SPC)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://66.90.93.122/soundfiles/nintendo-snes-spc/',
    files: [
      "donkey-kong-country/07%20Aquatic%20Ambiance.spc",
      "donkey-kong-country/10%20Mine%20Cart%20Madness.spc",
      "evo-search-for-eden/01%20The%20Origin%20of%20Gaia.spc",
    ]
  },
  {
    title: 'MIDI',
    url_prefix: 'songs/',
    files: [
      'all_night_long.mid',
      'christmas.mid',
      'KOOLTHIN.MID',
      'majicalljarr.mid',
      'neptune.mid',
      'rach3_1.mid',
      'rach3_2.mid',
      'rite-of-spring.mid',
      'STACCATO.MID',
      'Astro_Guy.mid',
      'DESCENT.MID',
      'GAME14.MID',
      'GAME18.MID',
      'GAME22.MID',
      'swanlake.mid',
      'syrinx.mid',
      'take5.mid',
      'Billy Joel - Just The Way You Are.mid',
      'prokofiev_vision_fugitives_22_(c)ungar.mid',
      'Prokofiev - Fugitive Visions, No. 1 - Lentamente.mid',
      'Prokofiev - Fugitive Visions, No. 2 - Andante.mid',
      'Prokofiev - Fugitive Visions, No. 14 - Feroce.mid',
      'Prokofiev - Fugitive Visions, No. 15 - Inquieto.mid',
      'Prokofiev - Fugitive Visions, No. 16 - Dolente.mid',
      'Prokofiev - Fugitive Visions, No. 17 - Poetico (Chris Todd).mid',
      'Prokofiev - Fugitive Visions, No. 17 - Poetico (David McDaniel).mid',
      'Prokofiev - Fugitive Visions, No. 18 - Con una dolce lentezza.mid',
      'Prokofiev - Fugitive Visions, No. 19 - Presto agitatissimo e molto accentuato.mid',
      'Prokofiev - Fugitive Visions, No. 20 - Lento. Irrealmente.mid',
      'Giesbrecht03.MID',
      'Teo04.MID',
    ],
  },
  {
    title: 'Local GME',
    url_prefix: 'songs/',
    files: [
      '01_Prelude.vgm',
      'vgm1.vgz',
      'vgm2.vgz',
      'vgm3.vgz',
      'vgm3.vgm',
      "04_realblue.nsf",
      "28_zjam300.nsf",
      "35_giantsteps.nsf",
      "Shovel_Knight_Music.nsf",
      "ThunderForce4.gym",
      'SFORCE2_003 - Town.gym',
      'SFORCE2_015 - Sad Theme 1.gym',
      'SFORCE2_027 - Goddess Mitula.gym',
      '04 - Lively Town.vgm',
      '14 - A Sorrowful Join.vgm',
      '24 - Elven Town.vgm',
      '30 - Water Goddess Mitula.vgm',
      'wt-01.spc',
      'monx-AllYouGot.nsf',
      'monx-herveroy.nsf',
      'monx-HuGH2.nsf',
      'monx-OlympicHeroes.nsf',
      'monx-trash.nsf',
      'scriabin2.nsf',
    ],
  },
  {
    title: 'Local XMP',
    url_prefix: 'songs/',
    files: [
      "dd-smkr.xm",
      "tr3cheato.it",
      "ut-firebr.xm",
      "Death Rally/MENUTUNE.S3M",
      "Jazz Jackrabbit/Menu.s3m",
      "One Must Fall 2097/03-MENU.S3M",
      "Unreal Tournament/16 - Razorback (Unreal Mix) [Peter Hajba].it",
    ],
  },
  {
    title: 'Super Nintendo (RSN) (currently disabled)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://snesmusic.org/v2/download.php?spcNow=',
    files: [
      "smw&.rsn",
      "yc&.rsn",
      "yi&.rsn",
    ]
  },
  {
    title: 'http://rainwarrior.ca (Brad Smith)',
    url_prefix: 'https://cors-anywhere.herokuapp.com/http://rainwarrior.ca/',
    files: [
      'music/moon8.nsfe',
      'projects/nes/2a03puritans.nsfe',
    ]
  },
];
