# Extended Module Player src/include/Makefile

TOPDIR	= ../..
DFILES	= Makefile config.h.in xmp.h common.h effects.h period.h driver.h \
	  mixer.h xxm.h getopt.h convert.h list.h readhuff.h readrle.h \
	  readlzw.h loader.h
DDIRS	=
CFILES	=
DCFILES	= config.h

all:

include $(TOPDIR)/Makefile.rules

