# Extended Module Player src/include/Makefile

TOPDIR	= ../..
DFILES	= Makefile config.h.in xmp.h xmpi.h effects.h period.h driver.h \
	  mixer.h xxm.h getopt.h formats.h convert.h
DDIRS	=
CFILES	=
DCFILES	= config.h

all:

include $(TOPDIR)/Makefile.rules

